import { test, expect } from '@playwright/test'

// No EN leak: these scaffold/EN strings must not appear anywhere in the PT-BR UI.
const FORBIDDEN_EN = [
  'Your projects', 'New project title', 'No projects yet',
  'Sign in', 'Send magic link', 'Describe what to build',
  'Slice for printing', 'Download .3mf', 'Print time', 'Filament',
  'Generating', 'Create Next App', 'Generated by create next app',
]

for (const vp of [
  { name: 'mobile', width: 390, height: 844 },
  { name: 'desktop', width: 1440, height: 900 },
] as const) {
  test(`sign-in: PT-BR, labelled, no EN leak (${vp.name})`, async ({ page }) => {
    await page.setViewportSize({ width: vp.width, height: vp.height })
    await page.goto('/sign-in')
    await expect(page.locator('h1')).toContainText('Entrar')
    await expect(page.getByLabel('E-mail')).toBeVisible()
    const html = await page.content()
    for (const en of FORBIDDEN_EN) expect(html).not.toContain(en)
  })

  test(`page metadata is PT-BR, lang=pt-BR (${vp.name})`, async ({ page }) => {
    await page.goto('/sign-in')
    await expect(page).toHaveTitle(/Gerador 3D/)
    await expect(page.locator('html')).toHaveAttribute('lang', 'pt-BR')
  })
}
