import { describe, it, expect } from 'vitest'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { zipSync } from 'fflate'
import { parse3mf } from '@/lib/3mf/parse-3mf'

const enc = new TextEncoder()

function zip3mf(rootModel: string, extra: Record<string, string> = {}): Uint8Array {
  const files: Record<string, Uint8Array> = {
    '3D/3dmodel.model': enc.encode(rootModel),
  }
  for (const [name, content] of Object.entries(extra)) {
    files[name] = enc.encode(content)
  }
  return zipSync(files)
}

function bbox(positions: Float32Array) {
  const min = [Infinity, Infinity, Infinity]
  const max = [-Infinity, -Infinity, -Infinity]
  for (let i = 0; i < positions.length; i += 3) {
    for (let a = 0; a < 3; a++) {
      min[a] = Math.min(min[a], positions[i + a])
      max[a] = Math.max(max[a], positions[i + a])
    }
  }
  return { min, max }
}

describe('parse3mf component composition (merge-lite bridge)', () => {
  it('parses a real cadpy two-body assembly: placement + per-object colors survive', async () => {
    // Fixture generated by cadpy (text-to-cad 0.3.10) from a labeled Compound:
    // base = red 20x20x4 plate at origin; peg = blue 6x6x10 box with component
    // transform rotate 45° about Z + translate (6, 5, 4).
    const bytes = new Uint8Array(
      await readFile(join(__dirname, '../fixtures/cadpy-two-body.3mf')),
    )
    const bodies = parse3mf(bytes)
    expect(bodies).toHaveLength(2)

    const base = bodies.find((b) => b.label.includes('base'))
    const peg = bodies.find((b) => b.label.includes('peg'))
    expect(base).toBeTruthy()
    expect(peg).toBeTruthy()

    // Object-level basematerials pindex: 0 → extruder A, 1 → extruder B.
    expect(base!.extruder).toBe('A')
    expect(peg!.extruder).toBe('B')

    const bb = bbox(base!.positions)
    expect(bb.min[0]).toBeCloseTo(-10, 3)
    expect(bb.max[0]).toBeCloseTo(10, 3)
    expect(bb.min[2]).toBeCloseTo(0, 3)
    expect(bb.max[2]).toBeCloseTo(4, 3)

    // Peg local corners (±3, ±3) rotated 45° → radius 3√2, then translated.
    const r = 3 * Math.SQRT2
    const pb = bbox(peg!.positions)
    expect(pb.min[0]).toBeCloseTo(6 - r, 3)
    expect(pb.max[0]).toBeCloseTo(6 + r, 3)
    expect(pb.min[1]).toBeCloseTo(5 - r, 3)
    expect(pb.max[1]).toBeCloseTo(5 + r, 3)
    expect(pb.min[2]).toBeCloseTo(4, 3)
    expect(pb.max[2]).toBeCloseTo(14, 3)
  })

  it('composes nested component transforms (child first, then parent)', () => {
    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
    <object id="2" type="model"><components>
      <component objectid="1" transform="1 0 0 0 1 0 0 0 1 10 0 0"/>
    </components></object>
    <object id="3" type="model"><components>
      <component objectid="2" transform="1 0 0 0 1 0 0 0 1 0 5 0"/>
    </components></object>
  </resources>
  <build><item objectid="3"/></build>
</model>`
    const bodies = parse3mf(zip3mf(model))
    expect(bodies).toHaveLength(1)
    expect(Array.from(bodies[0].positions)).toEqual([
      10, 5, 0, 11, 5, 0, 10, 6, 0,
    ])
  })

  it('flips triangle winding under a mirroring transform (det < 0)', () => {
    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
    <object id="2" type="model"><components>
      <component objectid="1" transform="-1 0 0 0 1 0 0 0 1 0 0 0"/>
    </components></object>
  </resources>
  <build><item objectid="2"/></build>
</model>`
    const bodies = parse3mf(zip3mf(model))
    expect(bodies).toHaveLength(1)
    // v1, v3, v2 order so the face normal still points outward after mirroring.
    expect(Array.from(bodies[0].positions)).toEqual([
      0, 0, 0, 0, 1, 0, -1, 0, 0,
    ])
  })

  it('ignores build-item transforms (plate placement is not model geometry)', () => {
    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
  </resources>
  <build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 125 125 0"/></build>
</model>`
    const bodies = parse3mf(zip3mf(model))
    expect(bodies).toHaveLength(1)
    expect(Array.from(bodies[0].positions)).toEqual([
      0, 0, 0, 1, 0, 0, 0, 1, 0,
    ])
  })

  it('resolves p:path component refs in the referenced file id namespace', () => {
    // Root has its own object id="1" (decoy, unreferenced) plus a component
    // wrapper pointing at id="1" INSIDE 3D/Objects/object_1.model — the Bambu
    // split layout. The parsed body must be the Objects-file mesh, not the decoy.
    const root = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:p="http://schemas.microsoft.com/3dmanufacturing/production/2015/06">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="9" y="9" z="9"/><vertex x="8" y="9" z="9"/><vertex x="9" y="8" z="9"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
    <object id="2" type="model"><components>
      <component p:path="/3D/Objects/object_1.model" objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 2"/>
    </components></object>
  </resources>
  <build><item objectid="2"/></build>
</model>`
    const objectFile = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
  </resources>
</model>`
    const bodies = parse3mf(
      zip3mf(root, { '3D/Objects/object_1.model': objectFile }),
    )
    expect(bodies).toHaveLength(1)
    expect(Array.from(bodies[0].positions)).toEqual([
      0, 0, 2, 1, 0, 2, 0, 1, 2,
    ])
  })

  it('throws on a component reference cycle instead of hanging', () => {
    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><components>
      <component objectid="2"/>
    </components></object>
    <object id="2" type="model"><components>
      <component objectid="1"/>
    </components></object>
  </resources>
  <build><item objectid="1"/></build>
</model>`
    expect(() => parse3mf(zip3mf(model))).toThrow(/cycle/i)
  })

  it('skips components whose target object is missing, keeping the rest', () => {
    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model"><mesh>
      <vertices>
        <vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/>
      </vertices>
      <triangles><triangle v1="0" v2="1" v3="2"/></triangles>
    </mesh></object>
    <object id="2" type="model"><components>
      <component objectid="9"/>
      <component objectid="1"/>
    </components></object>
  </resources>
  <build><item objectid="2"/></build>
</model>`
    const bodies = parse3mf(zip3mf(model))
    expect(bodies).toHaveLength(1)
    expect(Array.from(bodies[0].positions)).toEqual([
      0, 0, 0, 1, 0, 0, 0, 1, 0,
    ])
  })
})
